{
  parserClass="com.github.xiaolyuh.cls.parser.SimpleParser"
  parserUtilClass="com.github.xiaolyuh.cls.SimpleParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.xiaolyuh.cls.psi"
  psiImplPackage="com.github.xiaolyuh.cls.psi.impl"

  elementTypeHolderClass="com.github.xiaolyuh.cls.psi.SimpleTypes"
  elementTypeClass="com.github.xiaolyuh.cls.step3.SimpleElementType"
  tokenTypeClass="com.github.xiaolyuh.cls.step3.SimpleTokenType"

  psiImplUtilClass="com.github.xiaolyuh.cls.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="com.github.xiaolyuh.cls.psi.impl.SimpleNamedElementImpl"
  implements="com.github.xiaolyuh.cls.psi.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}