### Send POST request with json body
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send request with dynamic variables in request's body
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "uuid": "{{$random.uuid}}",
  "price": {{$random.integer()}},
  "price1": {{$random.integer(1,10)}},
  "price2": {{$randomInt}},
  "desc": "{{$random.alphabetic(10)}}",
  "desc1": "{{$random.alphanumeric(10)}}",
  "desc2": "{{$random.numeric(10)}}",
  "ts": {{$timestamp}},
  "value": "content"
}

###
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="first"; filename="input.txt"

< ./input.txt
--boundary
Content-Disposition: form-data; name="second"; filename="input-second.txt"

Text
--boundary
Content-Disposition: form-data; name="third";

< ./input.txt
--boundary--